services:
  - type: web
    name: job-scraper-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: EMAIL_ADDRESS
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: RECEIVER_EMAIL
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
